export const mapCreateActivityToDb = ({ companyId, lead, activity }) => ({
  company_id: companyId,
  lead_id: lead.id,
  activity_type: activity.activityType,
  subject: activity.subject,
  notes: activity.notes,
  outcome: activity.outcome,
  previous_stage: lead.current_stage ?? lead.initial_stage ?? lead.status,
  new_stage: activity.newStage,
  followup_date: activity.followUp?.date ?? null,
  followup_time: activity.followUp?.time ?? null,
  followup_via: activity.followUp?.via ?? null,
  activity_date: activity.activityDate,
  activity_time: activity.activityTime,
  created_by: activity.createdBy,
});

export const mapActivityResponse = (row = {}) => ({
  id: row.id,
  publicId: row.public_id,
  leadPublicId: row.lead_public_id,
  companyId: row.company_id,
  activityType: row.activity_type,
  subject: row.subject,
  notes: row.notes,
  outcome: row.outcome,
  previousStage: row.previous_stage,
  newStage: row.new_stage,
  followUp: {
    date: row.followup_date,
    time: row.followup_time,
    via: row.followup_via,
  },
  activityDate: row.activity_date,
  activityTime: row.activity_time,
  createdBy: row.created_by,
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});
