import { mapDashboardOverview } from "./dashboard.mapper.js";

const mockDashboard = {
  stats: [
    {
      id: "monthly-revenue",
      icon: "bi-currency-dollar",
      title: "Revenue - MTD",
      value: "$1.84M",
      subtitle: "Net margin $338K (18.4%)",
      trend: "22%",
      trendType: "success",
    },
    {
      id: "active-leads",
      icon: "bi-people-fill",
      title: "Active Leads",
      value: "47",
      subtitle: "Pipeline: $4.1M - Conv. 28%",
      trend: "12%",
      trendType: "success",
    },
    {
      id: "open-orders",
      icon: "bi-cart-check-fill",
      title: "Active Orders",
      value: "24",
      subtitle: "8 completed this month",
      trend: "3 urgent",
      trendType: "warning",
    },
    {
      id: "outstanding-client",
      icon: "bi-hourglass-split",
      title: "Outstanding - Client",
      value: "$312K",
      subtitle: "$84K overdue >30 days",
      trend: "7 overdue",
      trendType: "danger",
    },
    {
      id: "active-shipments",
      icon: "bi-truck-front-fill",
      title: "Active Shipments",
      value: "11",
      subtitle: "3 in transit - 2 at port",
      trend: "On track",
      trendType: "success",
    },
    {
      id: "compliance-alerts",
      icon: "bi-shield-exclamation",
      title: "Compliance Alerts",
      value: "5",
      subtitle: "2 expire <7 days",
      trend: "2 urgent",
      trendType: "danger",
    },
  ],
  alerts: [
    {
      id: "compliance-expiring",
      type: "warning",
      title: "2 compliance documents expiring within 7 days",
      message:
        "COA missing for #ORD-0119 (Chemtrex Vietnam) - MSDS expiring for #ORD-0117 (Petrochem Egypt)",
      actionLabel: "Review now",
      actionPath: "/dashboard/compliance",
    },
  ],
  businessOverview: {
    labels: ["Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    revenue: [1120, 980, 1340, 1180, 1520, 1510, 1840],
    margin: [185, 162, 238, 204, 274, 280, 338],
    orders: [8, 7, 11, 9, 14, 13, 16],
  },
  teamActivity: [
    {
      id: "priya-sharma",
      name: "Priya Sharma",
      role: "Sales",
      department: "Sales",
      avatarColor: "#3b82f6",
      status: "Online",
      statusVariant: "success",
      actionsToday: 24,
      lastActive: "Just now",
    },
    {
      id: "rahul-mehta",
      name: "Rahul Mehta",
      role: "Operations",
      department: "Operations",
      avatarColor: "#f59e0b",
      status: "Online",
      statusVariant: "success",
      actionsToday: 18,
      lastActive: "8 min ago",
    },
    {
      id: "neha-patel",
      name: "Neha Patel",
      role: "Accounts",
      department: "Accounts",
      avatarColor: "#8b5cf6",
      status: "Online",
      statusVariant: "success",
      actionsToday: 11,
      lastActive: "3 min ago",
    },
    {
      id: "amit-kumar",
      name: "Amit Kumar",
      role: "Sales",
      department: "Sales",
      avatarColor: "#ec4899",
      status: "Away",
      statusVariant: "warning",
      actionsToday: 7,
      lastActive: "45 min ago",
    },
    {
      id: "sunil-joshi",
      name: "Sunil Joshi",
      role: "Operations",
      department: "Operations",
      avatarColor: "#9ca3af",
      status: "Offline",
      statusVariant: "neutral",
      actionsToday: 2,
      lastActive: "Yesterday",
    },
  ],
  systemHealth: [
    {
      id: "api-service",
      service: "API Service",
      status: "operational",
      summary: "Operational",
    },
    {
      id: "database",
      service: "Database",
      status: "operational",
      summary: "99.98% uptime",
    },
    {
      id: "email-service",
      service: "Email Service",
      status: "operational",
      summary: "Operational",
    },
    {
      id: "pdf-generator",
      service: "PDF Generator",
      status: "warning",
      summary: "Degraded",
    },
    {
      id: "file-storage",
      service: "File Storage",
      status: "operational",
      summary: "Operational",
    },
    {
      id: "webhook-service",
      service: "Webhook Service",
      status: "operational",
      summary: "Operational",
    },
  ],
  recentOrders: [
    {
      id: "order-0124",
      avatar: "#124",
      orderNumber: "#ORD-0124",
      customer: "Al Khatib Trading - Kuwait",
      detail: "Caustic Soda 150 MT - FOB - LC - $45K - Mar 18 ship date",
      status: "PO Raised",
      statusVariant: "active",
    },
    {
      id: "order-0122",
      avatar: "#122",
      orderNumber: "#ORD-0122",
      customer: "Grupo Quimico SA - Brazil",
      detail: "Soda Ash 200 MT - CIF - TT - $38K - Mar 22 ship date",
      status: "Packaging",
      statusVariant: "active",
    },
    {
      id: "order-0119",
      avatar: "#119",
      orderNumber: "#ORD-0119",
      customer: "Chemtrex Vietnam - Vietnam",
      detail: "Nitrocellulose 5,000 KG - CFR - LC - $62K - Docs pending",
      status: "Doc Alert",
      statusVariant: "alert",
    },
    {
      id: "order-0110",
      avatar: "#110",
      orderNumber: "#ORD-0110",
      customer: "Chemplas Belgium - Belgium",
      detail: "Nitrocellulose 2,000 KG - CIF - TT - $26K - ETA Mar 22",
      status: "In Transit",
      statusVariant: "ship",
    },
    {
      id: "order-0104",
      avatar: "#104",
      orderNumber: "#ORD-0104",
      customer: "Chem Korea Ltd - South Korea",
      detail: "Soda Ash 150 MT - CAD - $28.5K - Delivered - payment overdue",
      status: "Payment Due",
      statusVariant: "pay",
    },
  ],
  moduleUsage: [
    {
      id: "leads",
      module: "Leads",
      usage: 95,
      count: 284,
      color: "#1f7a35",
    },
    {
      id: "quotations",
      module: "Quotations",
      usage: 70,
      count: 148,
      color: "#3b82f6",
    },
    {
      id: "orders",
      module: "Orders",
      usage: 55,
      count: 116,
      color: "#8b5cf6",
    },
    {
      id: "shipments",
      module: "Shipments",
      usage: 40,
      count: 84,
      color: "#f59e0b",
    },
    {
      id: "payments",
      module: "Payments",
      usage: 28,
      count: 59,
      color: "#ec4899",
    },
    {
      id: "reports",
      module: "Reports",
      usage: 18,
      count: 38,
      color: "#14b8a6",
    },
  ],
  quickActions: [
    {
      id: "new-lead",
      label: "Add Lead",
      icon: "bi-plus-circle-fill",
      path: "/dashboard/leads/new",
      variant: "primary",
    },
    {
      id: "manage-users",
      label: "Manage Users",
      icon: "bi-people",
      path: "/dashboard/settings/users",
      variant: "neutral",
    },
    {
      id: "reports",
      label: "Reports",
      icon: "bi-graph-up",
      path: "/dashboard/reports",
      variant: "neutral",
    },
    {
      id: "chemical-master",
      label: "Chemical Master",
      icon: "bi-droplet",
      path: "/dashboard/settings/chemical",
      variant: "neutral",
    },
    {
      id: "billing",
      label: "Billing",
      icon: "bi-credit-card",
      path: "/dashboard/settings/billing",
      variant: "neutral",
    },
    {
      id: "settings",
      label: "Settings",
      icon: "bi-gear",
      path: "/dashboard/settings",
      variant: "neutral",
    },
  ],
  quickNavigation: [
    {
      id: "users",
      label: "Users",
      icon: "bi-people-fill",
      path: "/dashboard/settings/users",
      category: "Admin",
    },
    {
      id: "roles",
      label: "Roles",
      icon: "bi-shield-lock",
      path: "/dashboard/settings/roles",
      category: "Security",
    },
    {
      id: "chemicals",
      label: "Chemicals",
      icon: "bi-droplet",
      path: "/dashboard/settings/chemical",
      category: "Master",
    },
    {
      id: "branding",
      label: "Branding",
      icon: "bi-palette",
      path: "/dashboard/settings/branding",
      category: "Company",
    },
    {
      id: "templates",
      label: "Templates",
      icon: "bi-file-earmark-text",
      path: "/dashboard/settings/documents",
      category: "Documents",
    },
    {
      id: "api-keys",
      label: "API Keys",
      icon: "bi-plug",
      path: "/dashboard/settings/api",
      category: "Integrations",
    },
    {
      id: "port-master",
      label: "Port Master",
      icon: "bi-ship",
      path: "/dashboard/settings/ports",
      category: "Logistics",
    },
    {
      id: "billing",
      label: "Billing",
      icon: "bi-credit-card",
      path: "/dashboard/settings/billing",
      category: "Account",
    },
    {
      id: "quick-reports",
      label: "Reports",
      icon: "bi-bar-chart",
      path: "/dashboard/reports",
      category: "Analytics",
    },
  ],
};

export const getDashboardOverview = async () =>
  mapDashboardOverview(mockDashboard);
