export const dashboardNavigation = [
  {
    id: "dashboard",
    label: "Dashboard",
    icon: "bi-speedometer2",
    path: "/dashboard",
    category: "Core",
  },
  {
    id: "leads",
    label: "Leads",
    icon: "bi-funnel",
    path: "/dashboard/leads",
    category: "CRM",
  },
  {
    id: "quotations",
    label: "Quotations",
    icon: "bi-file-earmark-text",
    path: "/dashboard/quotations",
    category: "Sales",
  },
  {
    id: "orders",
    label: "Orders",
    icon: "bi-cart-check",
    path: "/dashboard/orders",
    category: "Operations",
  },
  {
    id: "suppliers",
    label: "Suppliers",
    icon: "bi-building",
    path: "/dashboard/suppliers",
    category: "Procurement",
  },
  {
    id: "purchase-orders",
    label: "Purchase Orders",
    icon: "bi-bag-check",
    path: "/dashboard/purchase-orders",
    category: "Procurement",
  },
  {
    id: "shipments",
    label: "Shipments",
    icon: "bi-truck",
    path: "/dashboard/shipments",
    category: "Logistics",
  },
  {
    id: "compliance",
    label: "Compliance",
    icon: "bi-shield-check",
    path: "/dashboard/compliance",
    category: "Operations",
  },
  {
    id: "payments",
    label: "Payments",
    icon: "bi-cash-stack",
    path: "/dashboard/payments",
    category: "Finance",
  },
  {
    id: "reports",
    label: "Reports",
    icon: "bi-bar-chart",
    path: "/dashboard/reports",
    category: "Analytics",
  },
  {
    id: "settings",
    label: "Settings",
    icon: "bi-gear",
    path: "/dashboard/settings",
    category: "Admin",
  },
];

export const quickNavigationItems = [
  {
    id: "users",
    label: "Users",
    icon: "bi-people-fill",
    htmlSymbol: "👥",
    path: "/dashboard/settings/users",
    category: "Admin",
  },
  {
    id: "roles",
    label: "Roles",
    icon: "bi-shield-lock",
    htmlSymbol: "🔐",
    path: "/dashboard/settings/roles",
    category: "Security",
  },
  {
    id: "chemicals",
    label: "Chemicals",
    icon: "bi-droplet",
    htmlSymbol: "⚗️",
    path: "/dashboard/settings/chemical",
    category: "Master",
  },
  {
    id: "branding",
    label: "Branding",
    icon: "bi-palette",
    htmlSymbol: "🎨",
    path: "/dashboard/settings/branding",
    category: "Company",
  },
  {
    id: "templates",
    label: "Templates",
    icon: "bi-file-earmark-text",
    htmlSymbol: "📄",
    path: "/dashboard/settings/documents",
    category: "Documents",
  },
  {
    id: "api-keys",
    label: "API Keys",
    icon: "bi-plug",
    htmlSymbol: "🔌",
    path: "/dashboard/settings/api",
    category: "Integrations",
  },
  {
    id: "port-master",
    label: "Port Master",
    icon: "bi-ship",
    htmlSymbol: "🚢",
    path: "/dashboard/settings/ports",
    category: "Logistics",
  },
  {
    id: "billing",
    label: "Billing",
    icon: "bi-credit-card",
    htmlSymbol: "💳",
    path: "/dashboard/settings/billing",
    category: "Account",
  },
  {
    id: "quick-reports",
    label: "Reports",
    icon: "bi-bar-chart",
    htmlSymbol: "📊",
    path: "/dashboard/reports",
    category: "Analytics",
  },
];
