const QuotationPdfFooter = ({ company, quotation }) => (
  <footer className="quotation-pdf-footer">
    <div>
      {company?.name} - {company?.cin}
      <br />
      {company?.gst} - {company?.iec} - {company?.email}
    </div>
    <div>
      Generated by ChemCore CRM
      <br />
      Page 1 of 1 - {quotation?.quotationNumber}
    </div>
  </footer>
);

export default QuotationPdfFooter;
